import '@/app/globals.css'
import { Poppins } from "next/font/google";
import "swiper/css";
import "swiper/css/pagination";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
    title: 'insove doctor appointment',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <html lang="en">
            <body className={poppins.className}>
                {children}
            </body>
        </html>
    )
}

export default RootLayout;
