import '@/app/globals.css'
import { Poppins } from "next/font/google";
import "swiper/css";
import "swiper/css/pagination";

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
});

export const metadata = {
    title: 'Dashboard | Ordering System',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <html lang="en">
            <body className={poppins.className}>
                {children}
            </body>
        </html>
    )
}

export default RootLayout;
